### ISSUE TITLE
Needs more resources

### ISSUE THREAD

**Issue by Martin-Ting** [parkedwards/cs10-extra-resources#1]

**Comment by parkedwards** [comment]
Fair point

**Comment by Martin-Ting** [comment]
What are you planning on putting on this repo?

**Comment by parkedwards** [comment]
I wanted to comb through some of the links I sent you and lump them into groups, listing them here

**Comment by Martin-Ting** [comment]
Nice! I'd love to contribute to this for sure. Are you going to break out sections for technologies? eg. React, Redux, Databases, etc?

**Comment by parkedwards** [comment]
Yeah! I think that's a great idea.  I can add you to this repo, feel free to start adding stuff as you see fit
